# R ubuntu image https://hub.docker.com/u/rocker/
FROM rocker/r-ubuntu:18.04

MAINTAINER Choonhan Youn "cdesyoun@gmail.com"

# copy PrediXcan source code into /PrediXcan project directory
ARG PROJECT_DIR=/PrediXcan
RUN mkdir -p $PROJECT_DIR/Software

COPY ./Software/install_packages.R $PROJECT_DIR/Software/install_packages.R
COPY ./Software/requirements.txt $PROJECT_DIR/Software/requirements.txt

# set the working directory to the directory containing
# the source code.
WORKDIR $PROJECT_DIR/Software

RUN apt-get update && apt-get install -y python-pip python-dev

RUN pip install -r requirements.txt

# install R packages
# RUN Rscript -e "install.packages('data.table')"
RUN ./install_packages.R --error \
    methods \
    jsonlite \
    tseries

